### ISSUE TITLE
Missing assembly randomly?

### ISSUE THREAD

**Issue by InochiPM** [pleonex/Clypo#1]
![image](https://user-images.githubusercontent.com/13459080/139758635-bededbce-d21d-497b-a767-4f37b598da9c.png)
 I keep getting this error when i try to use Clypo now, it worked fine before but now it wont even run or show me the inner workings?

**Comment by pleonex** [comment]
Can you try try this one? I just recompiled the app with the latest. NET Core 3.1 in case that fixes the issue.
[Clypo_1_2_latest_netcore31.zip](https://github.com/pleonex/Clypo/files/7463554/Clypo_1_2_latest_netcore31.zip)

**Comment by InochiPM** [comment]
It works now! thanks!

**Comment by Blurro** [comment]
This version doesn't let me compile a bclyt out of an edited yml file. If I make no changes to the yml it works, otherwise it says
```
Unhandled exception. System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at Clypo.Yml2Clyt.Convert(Clyt source)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Yarhl.FileFormat.ConvertFormat.With(IConverter converter, Object src)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Yarhl.FileFormat.ConvertFormat.With[TConv,TParam](TParam param, Object src)
   at Yarhl.FileSystem.Node.TransformWith[TConv,TParam](TParam param)
   at Clypo.Console.Program.Import(String inputYml, String inputPo, String inputClyt, String output)
   at Clypo.Console.Program.Main(String[] args)
```
Also the normal ver used to work just fine up until today when it now gives this error 
```
Error:
  An assembly specified in the application dependencies manifest (Clypo.Console.deps.json) was not found:
    package: 'System.Composition.AttributedModel', version: '1.3.0'
    path: 'lib/netstandard2.0/System.Composition.AttributedModel.dll'
```
which is why i tried this ver but still no luck for me

**Comment by Blurro** [comment]
hm i think the first error happens with the normal ver too (tried it on a VM) guess I got a weird bclyt and gotta edit it the hard way
